### ISSUE TITLE
Requesting old events not returning anything

### ISSUE THREAD

**Issue by vinliao** [fiatjaf/go-nostr#7]
An event request, sent to `wss://relayer.fiatjaf.com`:

```
["REQ","p380vv138",{"ids":["b6a04d778cf5d991583b51112b78301f5dd8fe09824a12fee2b99281ffa879d3"]}]
```

It returns nothing - no notice, no nothin'. The same exact request, sent to `wss://nostr-pub.wellorder.net` (which runs `nostr-rs-relay`) gets me this result:

```
[
  "EVENT",
  "p380vv138",
  {
    "id": "b6a04d778cf5d991583b51112b78301f5dd8fe09824a12fee2b99281ffa879d3",
    "pubkey": "3bf0c63fcb93463407af97a5e5ee64fa883d107ef9e558472c4eb9aaaefa459d",
    "created_at": 1642152719,
    "kind": 1,
    "tags": [
      [
        "p",
        "b0635d6a9851d3aed0cd6c495b282167acf761729078d975fc341b22650b07b9"
      ],
      [
        "p",
        "e668a111aa647e63ef587c17fb0e2513d5c2859cd8d389563c7640ffea1fc216"
      ],
      [
        "e",
        "195418da26999c9ea0d3b594079c897c747ca0f3f16917e699aa739abac8243e"
      ],
      [
        "e",
        "8ea3f69a20e8630fc9f346a6dc635b1c3e6765f0e2561ced3439394098c541b4"
      ]
    ],
    "content": "what do you mean by \"branle is not for blog post\"? there is a client-side character limit on every note created on branle, but that doesn't prevent branle from displaying larger notes. and I think it is better for everybody is comments on a blog post can be made from branle.",
    "sig": "2250bd3f5cbcda6b6ad123108214195b04b479b3a36ea4486f1e422af872d8df7b1d6c9ced61cfa8e02a37fdbd7f57cb96d1ad7be61e673ac638316f6c5ca9a0"
  }
]
```

These requests were sent using Rust CLI client (https://github.com/vinliao/clust). This bug only happens whenever client requests old event - recent events works fine.

**Comment by fiatjaf** [comment]
That is simply because `wss://relayer.fiatjaf.com` doesn't have that event. Either it had it but deleted it as part of its normal eviction policy or it was never published to that relay in the first place. We can't ever expect all relays to have all events.

**Comment by vinliao** [comment]
That event appeared on `https://branle.netlify.app`. Is it because it pulled that specific event from other relays? (By the way, eviction policy seems to be about auto-deleting events, can you point me somewhere to read about that? It doesn't seem to be a part of NIP-01...)

**Comment by fiatjaf** [comment]
No, that's part of relayer.fiatjaf.com's internal policy, it's out of the spec.

branle.netlify.app can talk to any relay, not only relayer.fiatjaf.com. It comes with some relays by default but you can change.

**Comment by vinliao** [comment]
Understood. Thank you.
